env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - goos:
      - linux
      - darwin
      - windows
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip